### ISSUE TITLE
please delete my account

### ISSUE THREAD

**Issue by 0xadada** [jsonresume/registry-server#100]
username: `0xadada`

Seems i forgot the email address i used to generate the login, and now i can't relogin and there is no ability to remove without that email address.

**Comment by chiragjain23** [comment]
Please delete my account  : 2d366d17
I have tried  through curl and  resume settings  but nothing seems to work
Thanks

**Comment by Kautenja** [comment]
Also encountering an issue with this. Is there a password recovery feature in play somewhere?

EDIT: if not, could someone please remove the accounts `kautenja` and `christiankauten`? I had made these a few years ago when encountering some bugs with the CLI, but forgot the password and email before I could take the pages down.

**Comment by Durgon** [comment]
I am also encountering this issue. If there is no password recovery option, please delete accounts **jhammond** and **jthammond**.

**Comment by thomasdavis** [comment]
Service is shut down now
