### ISSUE TITLE
Vagrant VM no longer available.

### ISSUE THREAD

**Issue by RobertMortimer** [jsonresume/registry-server#40]
in base Vagrant file

The following box seems to be no longer available and 404s when I run it

```config.vm.box = "ubuntu/trusty64"```

Suggest 

```config.vm.box = "http://files.vagrantup.com/precise64.box"```

**Comment by ThomWright** [comment]
Hi Robert

The Vagrant box seems to be there: [ubuntu/trusty64](https://atlas.hashicorp.com/ubuntu/boxes/trusty64). It was even updated 18 minutes ago!

I just removed by local copy and re-ran the provision and it downloaded the box fine.

I'm going to close this for now but do feel free to re-open and let me know if you still have problems.
