### ISSUE TITLE
Registry-server Dependencies (npm body-parser)

### ISSUE THREAD

**Issue by RobertMortimer** [jsonresume/registry-server#41]
During provisioning of VM npm errors with the following:-

     ==> default: npm http GET https://registry.npmjs.org/resume-to-markdown
     ==> default: npm http GET https://registry.npmjs.org/resume-to-text
     ==> default: npm http GET https://registry.npmjs.org/sha256
     ==> default: npm http GET https://registry.npmjs.org/superagent
     ==> default: npm http GET https://registry.npmjs.org/tap-spec
     ==> default: npm http GET https://registry.npmjs.org/tape
     ==> default: npm ERR! Error: failed to fetch from registry: body-parser
     ==> default: npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
     ==> default: npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
     ==> default: npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
     ==> default: npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
     ==> default: npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
     ==> default: npm ERR!     at Request.emit (events.js:88:20)
     ==> default: npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
     ==> default: npm ERR!     at ClientRequest.emit (events.js:67:17)
     ==> default: npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
     ==> default: npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
     ==> default: npm ERR! You may report this log at:
     ==> default: npm ERR!     <http://bugs.debian.org/npm>
     ==> default: npm ERR! or use
     ==> default: npm ERR!     reportbug --attach /vagrant/npm-debug.log npm
     ==> default: npm ERR!
     ==> default: npm ERR! System Linux 3.2.0-23-generic
     ==> default: npm ERR! command "node" "/usr/bin/npm" "install"
     ==> default: npm ERR! cwd /vagrant
     ==> default: npm ERR! node -v v0.6.12
     ==> default: npm ERR! npm -v 1.1.4
     ==> default: npm ERR! message failed to fetch from registry: body-parser
     ==> default: npm ERR!
     ==> default: npm ERR! Additional logging details can be found in:
     ==> default: npm ERR!     /vagrant/npm-debug.log
     ==> default: npm not ok
     ==> default: Submodule 'resume-editor' () registered for path 'resume-editor'
     ==> default: fatal: unable to connect to github.com:
     ==> default: github.com[0: 192.30.252.128]: errno=Connection timed out
     ==> default: Unable to fetch in submodule path 'resume-editor'
     ==> default: MongoDB shell version: 2.0.4
     ==> default: connecting to: localhost:27017/jsonresume

Provisioned using precise64.box

**Comment by ThomWright** [comment]
I just re-provisioned and it worked for me. This combined with #40 suggests you might have been having some connectivity issues.

Closing for now, again feel free to re-open if this happens again.
