### ISSUE TITLE
What's the deploy period?

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/registry-server#54]
@thomasdavis, I can's see my update on http://registry.jsonresume.org/, please help, thanks.

**Comment by thomasdavis** [comment]
hrm should be auto deploying. let me check again

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by thomasdavis** [comment]
it should be deployed and auto deploying now

**Comment by PeterDaveHello** [comment]
Nice, leave issue opened for days to make sure that.

**Comment by PeterDaveHello** [comment]
@thomasdavis no work at all, I cannot see 09900b0977643fe18d7a4379ec32b37f7b6d76a4

**Comment by thomasdavis** [comment]
Mmmk must have configured legacy app

**Comment by PeterDaveHello** [comment]
Wait for your fixing, ha ...

**Comment by thomasdavis** [comment]
=D deploying now. third time lucky

**Comment by PeterDaveHello** [comment]
But now I got error xD:
>　Cannot GET /

**Comment by thomasdavis** [comment]
That is the default home page atm.

http://registry.jsonresume.org/thomasdavis?theme=paper

Actually it should display the resume builder hrmmm

**Comment by PeterDaveHello** [comment]
But I have no problem locally.

**Comment by PeterDaveHello** [comment]
![Imgur](http://i.imgur.com/if06KA2.png)

**Comment by ThomWright** [comment]
What version of Node is running in production?

**Comment by PeterDaveHello** [comment]
In fact, the CI build runs on all the common versions of nodejs, see 10a41bf638568cc5c6053fe87e8200d70a20c731

**Comment by ThomWright** [comment]
Last time I checked some of them were failing, maybe that's been fixed (can't look right now).

**Comment by PeterDaveHello** [comment]
My local env:

Distro:
> Distributor ID: Ubuntu
> Description:    Ubuntu 14.04.2 LTS
> Release:        14.04
> Codename:       trusty
Kernel:
> Linux vmlab 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
nodejs:
> 0.10.33-1chl1~trusty1

**Comment by PeterDaveHello** [comment]
> Last time I checked some of them were failing, maybe that's been fixed (can't look right now).
Now passed all the tests on all envs.

**Comment by thomasdavis** [comment]
Setting production to 0.12.2

**Comment by PeterDaveHello** [comment]
I think 0.10 will be better, we used it for a long time, and not so familiar with v0.12

**Comment by thomasdavis** [comment]
Running node server.js on localhost no longer displays the editor at the homepage. Someone must have removed it which is not the biggest deal, not that many people used it. But will bring it back up nontheless.

**Comment by thomasdavis** [comment]
@PeterDaveHello strange that you still get that home page

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello strange that you still get that home page

I'm sure I have no problem on my machine.

**Comment by thomasdavis** [comment]
Are you on the most recent commit?

**Comment by PeterDaveHello** [comment]
Yes, the latest.

**Comment by thomasdavis** [comment]
oh the resume-builder is a sub module and heroku is not running "git submodule update --init"

**Comment by PeterDaveHello** [comment]
lol ...

**Comment by thomasdavis** [comment]
```
[submodule "json-builder"]
	path = json-builder
	url = https://github.com/erming/json-builder
[submodule "resume-editor"]
	path = resume-editor
	url = https://github.com/erming/resume-editor
```

https://devcenter.heroku.com/articles/git-submodules

Still not working grrr

**Comment by thomasdavis** [comment]
Hrmm very strange

```
remote: Git submodules detected, installing:
remote: Submodule 'editor' (https://github.com/erming/resume-editor) registered for path 'editor'
remote: Cloning into 'editor'...
remote: Submodule path 'editor': checked out '5132d883f1ca2fade07b043dc46d73a6d24b822e'
remote: Submodule 'json-builder' (https://github.com/erming/json-builder) registered for path 'json-builder'
remote: Cloning into 'json-builder'...
remote: Submodule path 'editor/json-builder': checked out '453435138291b56787e0f42a0808e7166642e887'
remote: 
remote: Compressing source files... done.
remote: Building source:
```

It is working now after manually pushing to heroku.

Though the repo is configured via web hooks to auto deploy when it detects a new commit on github.

**Comment by PeterDaveHello** [comment]
Still I got error:
>　Cannot GET /

**Comment by thomasdavis** [comment]
Try again.

I've gotta disable the github+heroku auto deploy, doesn't run submodules and breaks it -.- so annoying.

**Comment by PeterDaveHello** [comment]
@thomasdavis what about add me in heroku collaborator and check if I can help?

**Comment by thomasdavis** [comment]
done ^^

**Comment by PeterDaveHello** [comment]
will do it soon, maybe next holiday :)

**Comment by PeterDaveHello** [comment]
I didn't see it, seems you added me to a wrong team?

**Comment by thomasdavis** [comment]
I think you have to accept the invite in your inbox.

**Comment by PeterDaveHello** [comment]
okay ... wait a min ...

**Comment by PeterDaveHello** [comment]
I only receive mail about "fpv-racing" but no jsonresume, and I think I don't need the mail confirm.

**Comment by thomasdavis** [comment]
![screenshot from 2015-05-18 23 53 03](https://cloud.githubusercontent.com/assets/416209/7682135/18334090-fdb9-11e4-9831-4a681fe2b661.png)

**Comment by PeterDaveHello** [comment]
Oh, I mean on heroku!

**Comment by thomasdavis** [comment]
r0fl sorry. I removed you from the fpv racing one and added you to jsonresume

**Comment by PeterDaveHello** [comment]
Okay, great, btw, I have same question on https://github.com/jsonresume/theme-manager

**Comment by thomasdavis** [comment]
Lets move this to #jsonresume on freenode

**Comment by ThomWright** [comment]
A bit off-topic here, but how would you feel about using [Gitter](https://gitter.im/) for chat? Seems nicely integrated, could be cool :)

**Comment by thomasdavis** [comment]
It's setup for our other project cdnjs -> http://gitter.im/cdnjs/cdnjs

But have sort of just found it laggier in general. But I think it makes sense to change over to Gitter, will have to update some of the links on homepage.

**Comment by thomasdavis** [comment]
Yeah lets use it

**Comment by thomasdavis** [comment]
https://gitter.im/jsonresume/public
