### ISSUE TITLE
Online editor not working

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/registry-server#68]
The link - http://registry.jsonresume.org/ on https://jsonresume.org/getting-started/ shows `Cannot GET /`

**Comment by PeterDaveHello** [comment]
cc @thomasdavis

**Comment by dbkaplun** [comment]
:+1: `Cannot GET /`

**Comment by PeterDaveHello** [comment]
I can run the server properly in my machine, and didn't see error on our server, ping @thomasdavis

**Comment by PeterDaveHello** [comment]
It works now, looks like fixed by breaking it and resume it.

**Comment by erming** [comment]
Ping @PeterDaveHello and @rolandnsharp:

I just pushed some updates to this repository (the package.json was really old and I also updated resume-editor). However, the the webpage is still returning `Cannot GET /`. Took me a while to figure out that it wasn't hosted on Heroku anymore, so I guess it's hosted by you guys somewhere else (or am I wrong about this?).

Anyway, `/` worked on my local machine. It's supposed to server static files, so there must be some problem with the express server in `server.js`.

**Comment by thomasdavis** [comment]
Still on heroku, I think I know the solution for this bug

**Comment by thomasdavis** [comment]
http://registry.jsonresume.org/

alright just gotta get assets loading now =D

**Comment by PeterDaveHello** [comment]
@thomasdavis What's the problem actually?

**Comment by swarajgiri** [comment]
@thomasdavis - It's down again. http://registry.jsonresume.org/

**Comment by PeterDaveHello** [comment]
I just redeployed and seems it works now, still don't know the problem. @thomasdavis ?

**Comment by my8bit** [comment]
Same story.

**Comment by PeterDaveHello** [comment]
Working on it by the same trick ...

**Comment by PeterDaveHello** [comment]
It works now.

**Comment by ishu3101** [comment]
It's down again.

**Comment by thomasdavis** [comment]
I removed it, didn't think it was that useful. Will work  on a replacement
page tonight.

On Thu, Apr 28, 2016 at 2:33 PM, ishu3101 <notifications@github.com> wrote:

> It's down again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/registry-server/issues/68#issuecomment-215307754>
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by ishu3101** [comment]
I found the editor useful. Could you redeploy it until the replacement is done? 

Is the replacement going to better than the current one?

**Comment by thomasdavis** [comment]
I can re-deploy it tonight.

How were you using it might I ask?

Do you import and export your resume each time?

Would it be easier with just a text editor on the left and a theme updater on the right?

Those form inputs seem to be too clunky.

**Comment by ishu3101** [comment]
Having the editor was at least better than not having it at all. Yes, the editor was clunky and could be improved to make it a lot better. 

I only used the editor once so did not have to import & export the resume each time. 

The new editor should still have a form where the user can enter the details. Probably could use github to sync your resume so would not have to import/export each time.

**Comment by thomasdavis** [comment]
Sorry for breaking that on you, I didn't know anybody used it =D I should probably put some tracking on it. I've just commited it back and it should hopefully be back online soon.

**Comment by ishu3101** [comment]
Thanks. What features do you plan to have for the new editor. If you need inspiration have a look at http://www.enhancv.com/

**Comment by PeterDaveHello** [comment]
Now works.
