### ISSUE TITLE
Ability to reset password

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/registry-server#77]
@joryhatton:

> Is there a way to reset your password? I forgot my old one, and I can't change it on my account. I would also like to change my resume to password protected and cannot figure out how. Thanks.

**Comment by joryhatton** [comment]
Still no fix here? Is there a manual reset request available in the meantime? I would like to publish an updated resume, but I still can't access my account.

**Comment by pearsonc** [comment]
Does anyone know if this functionality has been added yet?

**Comment by digitaldonkey** [comment]
No PW Reset?
Are you serious?
How Do I DELETE that now?

**Comment by thomasdavis** [comment]
Hey Thornton, just send me an email thomasalwyndavis@gmail.com and I will
clear that up for you

**Comment by GabLeRoux** [comment]
Any progress on this? I had some troubles when syncing my password manager and turns out I only lost password for this. So password reset can be done manually?

**Comment by jmsalcido** [comment]
yah I forgot it h4h4, any update on this?

**Comment by thomasdavis** [comment]
@jmsalcido is your username h4h4?

**Comment by LewisWatson** [comment]
I'm also having issues logging into my account. I'm getting email/password incorrect.

**Comment by aodj** [comment]
So is the conclusion that there is no functionality to reset password/recover accounts? What's needed to make this happen?

**Comment by mushahid54** [comment]
I'm also having issues logging into my account. forgot my password unable to retrieve it is there any way to do it. Any help would be appreciated.

**Comment by sharils** [comment]
Hi @thomasdavis ,

bq. Hey Thornton, just send me an email thomasalwyndavis@gmail.com and I will clear that up for you

I wrote a mail to you on Nov 8. Would you mind remove my json resume account? Or simply reset my password to something and send the new password back to me. My username is lhcity. Thanks.

Best,
sharils

**Comment by thomasdavis** [comment]
Sorry guys, will clean the requested accounts tonight.

**Comment by sharils** [comment]
Sorry @thomasdavis I have to bother you again, but my json resume is still there, would you mind delete it for me? My username is *lhcity*. I'm really sorry to have to bother you again and again. I'm so sorry about that. :(

**Comment by thomasdavis** [comment]
@sharils taken care of.

**Comment by luckyrabbitllc** [comment]
Is this for real? No password management?

**Comment by nancysarahi** [comment]
Since I am in the same boat, sorry but need to reset password or please delete "nancysarahi". I would appreciate it!
