### ISSUE TITLE
Public site is down

### ISSUE THREAD

**Issue by adrianblynch** [jsonresume/registry-server#81]
Sorry if this is the wrong place to highlight this.

The site seems to be down: http://registry.jsonresume.org/

<img width="451" alt="screen shot 2016-01-27 at 17 51 43" src="https://cloud.githubusercontent.com/assets/4160967/12622739/aac1e10a-c51e-11e5-8a03-7ce0a38dd128.png">

**Comment by itsdn** [comment]
Experiencing this too.

**Comment by adrianblynch** [comment]
Is there anything anyone can do to help with this? If it's due to financial constraints, could that be expressed? I think there would be a number of organisations that might back it with some cold hard.

**Comment by PeterDaveHello** [comment]
I'll take a look.

**Comment by PeterDaveHello** [comment]
Okay there may be some problems, I submitted ticket to heroku and ask for help. cc @thomasdavis

**Comment by thomasdavis** [comment]
Still waiting on Heroku's support team to change a setting.

**Comment by PeterDaveHello** [comment]
The reply from heroku is very unprofessionl and didn't help at all, so bad.

**Comment by thomasdavis** [comment]
We can close that ticket, I am taking care of it in another. It is a
billing problem and I am migrating the app to another account. And already
have, but I can't redirect the domain until they remove the domain from the
old account.
