### ISSUE TITLE
Site Not Rendering Registered Resumes

### ISSUE THREAD

**Issue by SingleShot** [jsonresume/registry-server#82]
I just registered my resume at http://registry.jsonresume.org/SingleShot yesterday - looked great. Today, when I hit that URL it is a mess of HTML and json tags. The example resumes fail as well, e.g. http://registry.jsonresume.org/thomasdavis.

**Comment by thomasdavis** [comment]
I'm on this one....

**Comment by chiefy** [comment]
@thomasdavis looks like the registry site is throwing `50x` when requesting anyone's resume. Any ideas?

**Comment by thomasdavis** [comment]
https://github.com/jsonresume/registry-server/issues/105
