### ISSUE TITLE
Delete Resume published as guest

### ISSUE THREAD

**Issue by einSelbst** [jsonresume/registry-server#88]
I also didn't realize that it could be a problem to remove a resume published as a guest.
Now I would like them to be removed.

https://registry.jsonresume.org/62938fa0
https://registry.jsonresume.org/57d108f3

There was an issue in resume-cli where someone suggested opening an issue here.
https://github.com/jsonresume/resume-cli/issues/181

While it would be nice if someone could just delete my 2 resumes I would also like to know what needs to be done to built that functionality. Thanks in advance, Silvio

**Comment by 0xcrypto** [comment]
I am facing the same problem :(

**Comment by thomasdavis** [comment]
This is now resolved, will close in favor of other issue.
