### ISSUE TITLE
'Application error on heroku' shows up when trying to access published resume.

### ISSUE THREAD

**Issue by Faiz7412** [jsonresume/registry-server#90]
I tried accessing two resumes that I published, none of them are accessible anymore. I'm pretty sure there was no error in json file as I saw the published resume a few days ago

**Comment by thomasdavis** [comment]
Thanks for the report, I've lodged a ticket with the database host. It seems to be down and I have no options to recover so waiting it out.

**Comment by thomasdavis** [comment]
The registry is backup, going to email out a backup of each persons resume as there was a bit of a scare that the data wasn't backed up properly.
