### ISSUE TITLE
Registry is offline

### ISSUE THREAD

**Issue by felipeamarante** [jsonresume/registry-server#92]
Looks like heroku set up guys up.

https://registry.jsonresume.org/feamarante

SELECTED: Publish as guest.
- publishing...{ [Error: Not Found]
  original: null,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
        statusCode: 404,
        statusMessage: 'Not Found',

**Comment by thomasdavis** [comment]
Thanks looking into it

**Comment by felipeamarante** [comment]
Heroku is back, but now seems that we have 502. Please let me know if you need help to troubleshoot.

https://registry.jsonresume.org/feamarante

err snippet: 
www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">CloudFlare</a></span>\n</p>\n</div> \n</div> \n</div> \n"},"status":502}

**Comment by thomasdavis** [comment]
Thanks, looking into it

**Comment by thomasdavis** [comment]
Backup again, problem with theme server this time. Will try get these services more rock solid =(

**Comment by thomasdavis** [comment]
Down again lol Putting some grunty servers behind it at the same time for fun

**Comment by thomasdavis** [comment]
Back up and meatier
