### ISSUE TITLE
Resume server is down

### ISSUE THREAD

**Issue by boris-hamanov** [jsonresume/registry-server#94]
Error 502 Ray ID: 32fa896852914032 • 2017-02-11 20:26:36 UTC
Bad gateway
![screenshot 2017-02-11 22 26 56](https://cloud.githubusercontent.com/assets/16512778/22857202/3b07b7ec-f0a9-11e6-9729-21ba47106eef.png)

**Comment by shailendher** [comment]
The server is down again. 

https://registry.jsonresume.org/ -> works
https://registry.jsonresume.org/<profile> -> does not work.

which probably means that it's a server side error? Perhaps @thomasdavis  can help?

**Comment by PeterDaveHello** [comment]
Now down again, @thomasdavis would you like to take a look?

**Comment by thomasdavis** [comment]
Billing issue, working on it.

**Comment by PeterDaveHello** [comment]
@thomasdavis anything I can help here? It's still down 😟

**Comment by PeterDaveHello** [comment]
Should be good now

**Comment by bmm85** [comment]
Down once again.

**Comment by thomasdavis** [comment]
Will fix it up.

**Comment by mcarbonneaux** [comment]
Down again....
