### ISSUE TITLE
Resume Registry is down again...

### ISSUE THREAD

**Issue by philip-ulrich** [jsonresume/registry-server#98]
Gateway timeouts again. 

Error 504 Ray ID: 3cde80add9d45909 • 2017-12-16 03:19:43 UTC
Gateway time-out
You
Browser
Working
Dallas
Cloudflare
Working
registry.jsonresume.org
Host
Error
What happened?
The web server reported a gateway time-out error.

@thomasdavis

**Comment by nomadster** [comment]
Will the free registry service will come up again or have you just dismissed it?

**Comment by nomadster** [comment]
The same is happening for themes.jsonresume.org

**Comment by kseyhan** [comment]
Hello, is this Project finaly down? The infrastructure like the registry and theme subdomains are dead since days.

**Comment by philip-ulrich** [comment]
If the author is no longer interested in maintaining this, does anyone want to resurrect it with me?

**Comment by hjhart** [comment]
@philip-ulrich I'm gettin' into this stuff right now and would be willing to help work on it.

Noticed this issue https://github.com/jsonresume/theme-manager/issues/37 is related. 

@thomasdavis What can we help? Would a sync up via chat, voice or video speed things up?

**Comment by kseyhan** [comment]
I guess @thomasdavis is having a financial crisis right now. His personal website linked on this profile page is down aswell but he seems to be alive since there is some github activity.

**Comment by philip-ulrich** [comment]
@PeterDaveHello Do you have any insight into this since you seem to be. the only active one here?

**Comment by philip-ulrich** [comment]
jsonresu.me is available for purchase.. 🤣

**Comment by PeterDaveHello** [comment]
That's true, but I believe the problem is more beyond the domain, with all due respect, the same problem appears in the npm packages, the other maintainers have no permission to release new version of dated packages in the meantime, that's not too much that we can do unless we've decided to fork to a whole new project. cc @jsonresume/core-developers @jsonresume/owners @jsonresume/standards-committee

**Comment by PeterDaveHello** [comment]
The effort would be high to start a new project and I don't want to separate the project, maybe just wait for @thomasdavis response :)

**Comment by philip-ulrich** [comment]
Fair. Hopefully the org can get structured a little better to help with issues like this. FWIW I know it's more than just getting a new domain, but ensuring you have one available is always a good first step. 😄

**Comment by philip-ulrich** [comment]
IMO having something up (and up realiably) is more important than the existing data (especially if it’s not coming back up). I’m not sure how long it’s been down this time, but it certainly seems down more than it is up right now... Anyone using this service would hopefully know how to use and have their resume hosted in a git repository/host or other version control software/host. I’m just happy I’m not job hunting right now or I’d be a little sad. 

FWIW I think digital ocean still does free hosting for non-profits. We could get it up and running there likely in a small amount of time. Then (assuming it’s not highly available in its current state) we’d need to aim to make the application stateless and throw it behind a load balancer to help keep the uptime...  up. We could make sure the access is shared to that account so multiple people have access and also make sure there are at least a couple working logins to the server should they be needed.

**Comment by nomadster** [comment]
My offer is still valid. I have a 2Gb RAM, 2vCpus, 60Gb SSD droplet i'm using to host a low traffic website

**Comment by thomasdavis** [comment]
Moving cities at the moment.

Trying to find time to bring servers back online.

@PeterDaveHello Do you not have admin access to org?

**Comment by PeterDaveHello** [comment]
@thomasdavis good to see you back, my permission is currently on GitHub only.

**Comment by kseyhan** [comment]
can we maybe help somehow to get those servers up again?

**Comment by thomasdavis** [comment]
So the registry goes down on occasion due to billing problems and server errors.

I am looking at moving everything to a server-less architecture to alleviate both problems. (cheaper and no server)

Does anyone have any recommendations on SAAS or frameworks for deploying server-less?

@PeterDaveHello I have elevated you to owner of the repo also.

**Comment by chiefy** [comment]
@thomasdavis 

- http://apex.run/
- https://serverless.com/

**Comment by PeterDaveHello** [comment]
@thomasdavis you mean heroku? I didn't see any notification or updates.

**Comment by kseyhan** [comment]
@thomasdavis maybe this is an alternative aswell. https://www.openshift.com/community/programs/grants/

**Comment by thomasdavis** [comment]
Was rewriting the server to use serverless.com last night on Google Cloud Functions. But apparently GCF cannot access Cloud SQL -.-

Will try again with AWS this time.

**Comment by nomadster** [comment]
I still have that droplet :)

**Comment by DandyDev** [comment]
Devil's Advocate here: why jump on the serverless hypetrain and completely rewrite the application (which was otherwise functioning perfectly fine), without evidence that it will actually reduce costs? Costs, I might add, that probably don't exceed $10/month...

**Comment by thomasdavis** [comment]
@DandyDev Absolutely hear you. It was more an upskilling exercise whilst maintaining exercise on my behalf. And although billing has been an issue, my poor setup of the server has also added to the downtime. Logs making the disk run out, random restarts without proper boot scripts. The solution is to move to Heroku which would solve essentially everything. The only problem being the nature of the theme server (dynamic themeing) makes it hard to use Heroku. Though there are work arounds as per usual in tech, so I will most likely just fix up the servers and put them on Heroku.

**Comment by EmilStenstrom** [comment]
I like the idea of a json-schema for CV:s, but without the registry working, the whole idea falls. Is it time to make this project more decentralized, so it's not dependent on a single developer's free time?

**Comment by nomadster** [comment]
Is this project still alive? @thomasdavis I do still have that droplet. Is your traffic below 3TB/month?

**Comment by thomasdavis** [comment]
Looking into it. Will ask DigitalOcean for sponsorship too.

**Comment by nomadster** [comment]
Thanks, this service is awesome! Just keep it working :)

**Comment by icorbrey** [comment]
I would love to help work on this project if y'all need an extra set of hands.

**Comment by adityatandon007** [comment]
@thomasdavis when can I expect this to be up? I know you've working on this but what is the current status of this? I love this service and I wanted to update my resume and when I went there it was down. I would love to see this back up as soon as possible. :+1:

**Comment by gesposito** [comment]
> @thomasdavis
> 
> * http://apex.run/
> * https://serverless.com/

There's also `now`
https://zeit.co/now
that might require less effort

**Comment by thomasdavis** [comment]
Everything is moving serverless and credentialless

https://github.com/jsonresume/registry-server/issues/105

@adityatandon007 Did yuo get a backup of your resume?
